#Config is set up 'by extension', it's a minor nuisance of Chrome
#extension security model that the runtime id changes based on the source
#but, a small convenience for debug local with a local server vs
#production with a live server

#root key is the chrome extension runtime id
default:
  reload: true
  signallingServer: ws://localhost:9000
cmkckpjleijfldmfnabklbcldhcemgnh:
  reload: false
  signallingServer: ws://workrooms.glgresearch.com/workrooms/
